
#
# Super simple example of a Dockerfile
#
FROM ubuntu:latest
MAINTAINER Andrew Odewahn "odewahn@oreilly.com"

#RUN apt-get update
#RUN apt-get install -y python python-pip wget
#RUN pip install Flask
COPY ./socket-server /socket-server
RUN chmod +x /socket-server/test.sh
WORKDIR /home
CMD ["/socket-server/test", "--port", "9345", "--host", ""]
