name : slack
on: check_run
jobs:
  slack:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL1 }}
    - uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        author_name: Integration Test # default: 8398a7@action-slack
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL1 }} # required
      if: always()
   
