name: upload artifacts
on: push 

jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: socket-server
        path: socket-server
   
     
      
